<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hervent | Corporate Gift Custom untuk Perusahaan</title>
    <meta name="description" content="Corporate gift, promotional merchandise, dan souvenir kantor custom sejak 2009.">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body>
    @include('partials.header')
    <main>
        <section id="beranda" class="hero"><div class="container hero-inner"><span class="eyebrow">Dipercaya 4.500+ klien korporasi & instansi</span><h1>Souvenir Kantor & Corporate Gift Custom <em>untuk Perusahaan Anda</em></h1><p class="hero-copy">HERVENT membuat hadiah korporat yang mewakili nama baik perusahaan Anda. Desain gratis, produksi terkontrol, kirim ke seluruh Indonesia.</p><div class="hero-actions"><a class="button button-light" href="https://wa.me/62811912502" target="_blank">&#9993; Konsultasi Gratis</a><a class="button button-outline" href="#kalkulator">&#8595; Hitung Estimasi Budget</a></div><div class="hero-stats"><div><strong>Sejak 2009</strong><span>17 tahun pengalaman</span></div><div><strong>50 pcs</strong><span>Minimum order</span></div><div><strong>Gratis</strong><span>Desain & mockup</span></div><div><strong>PPN</strong><span>Faktur pajak tersedia</span></div></div></div></section>
        <section class="trusted-section"><div class="container trusted-heading"><p class="kicker">Dipercaya oleh</p><h2><span class="counter" data-target="4500">0</span>+ Brand & Perusahaan Indonesia</h2></div><div class="client-strip"><div class="client-track"><span>PERBANKAN</span><span>FMCG</span><span>TEKNOLOGI</span><span>PEMERINTAH</span><span>PERGURUAN TINGGI</span><span>STARTUP</span><span>PERBANKAN</span><span>FMCG</span><span>TEKNOLOGI</span><span>PEMERINTAH</span><span>PERGURUAN TINGGI</span><span>STARTUP</span></div></div></section>
        <section id="produk" class="section"><div class="container"><div class="section-heading catalog-heading"><div><p class="kicker">Best seller</p><h2>Produk favorit untuk momen yang tidak boleh biasa.</h2><p class="section-intro">Paket yang paling sering dipilih klien korporasi. Semua bisa disusun ulang isinya sesuai budget dan momen Anda.</p></div><a class="text-link" href="{{ route('products.index') }}">Lihat semua produk &#8594;</a></div><div class="product-grid best-seller-grid">@foreach($bestSellers as $product)<a class="product-card best-seller-card" href="{{ route('products.index') }}#product-{{ $product->id }}"><div class="product-image"><img src="{{ $product->image_url }}" alt="{{ $product->name }}" loading="lazy"><span class="product-tag">{{ $loop->first ? 'Terlaris' : ($loop->last ? 'Favorit HR' : 'Pilihan klien') }}</span></div><div class="product-info"><span class="product-category">{{ $product->category_label }}</span><h3>{{ $product->name }}</h3><p>{{ $product->description }}</p><div class="product-meta"><span class="price">Mulai {{ $product->price_min ? 'Rp '.number_format($product->price_min, 0, ',', '.') : $product->price_label }}</span><span class="moq">/ pcs</span></div></div></a>@endforeach</div></div></section>
        <section class="section category-section"><div class="container"><div class="section-heading catalog-heading"><div><p class="kicker">Kategori produk</p><h2>Temukan paket yang pas untuk penerima Anda.</h2><p class="section-intro">Dari gift set eksekutif sampai perlengkapan event, pilih koleksi yang paling sesuai dengan cerita brand Anda.</p></div><a class="text-link" href="{{ route('products.index') }}">Buka katalog &#8594;</a></div><div class="category-grid">@foreach($categories as $category)<a class="category-card" href="{{ route('products.index', ['category' => $category]) }}"><span class="category-index">0{{ $loop->iteration }}</span><div><span>{{ \Illuminate\Support\Str::headline($category) }}</span><small>{{ $categoryCounts[$category] ?? 0 }} koleksi tersedia</small></div><b>&#8594;</b></a>@endforeach</div></div></section>
        <section id="keunggulan" class="section feature-band"><div class="container feature-grid"><div><p class="kicker">Kenapa Hervent</p><h2>Pengadaan gift tanpa drama dan tanpa kejutan biaya.</h2><p class="muted">Kami membantu Anda terlihat siap di setiap momen penting. Dari brief pertama sampai paket tiba, semua bergerak dengan satu tim.</p></div><div class="feature-list"><article class="feature-item"><span class="feature-number">01</span><h3>Kurasi yang relevan</h3><p>3-5 opsi paket disusun berdasarkan penerima, momen, dan budget Anda.</p></article><article class="feature-item"><span class="feature-number">02</span><h3>Mockup gratis</h3><p>Logo dan kemasan divisualkan sebelum produksi berjalan.</p></article><article class="feature-item"><span class="feature-number">03</span><h3>QC terkontrol</h3><p>Foto quality check dikirim sebelum paket meninggalkan gudang kami.</p></article><article class="feature-item"><span class="feature-number">04</span><h3>Distribusi nasional</h3><p>Kirim ke satu alamat atau banyak cabang di seluruh Indonesia.</p></article></div></div></section>
        <section id="kalkulator" class="section"><div class="container calculator"><div><p class="kicker">Alat bantu</p><h2>Mulai dari angka yang Anda punya.</h2><p class="muted">Dapatkan kisaran budget dalam hitungan detik. Angka ini menjadi titik awal diskusi, bukan harga final.</p></div><div class="calculator-box"><div class="form-row"><div><label for="quantity">Jumlah penerima</label><input id="quantity" type="number" min="1" value="100"></div><div><label for="budget">Budget per orang</label><select id="budget"><option value="100000">Rp 50 - 150 ribu</option><option value="200000">Rp 150 - 300 ribu</option><option value="400000">Rp 300 - 500 ribu</option><option value="700000">Di atas Rp 500 ribu</option></select></div></div><a class="button" href="https://wa.me/62811912502" target="_blank">Kirim kebutuhan via WhatsApp</a><div class="calc-result"><span class="muted">Estimasi total paket</span><strong id="estimate">Rp 10.000.000</strong></div></div></div></section>
        <section id="proses" class="section process"><div class="container"><div class="section-heading"><div><p class="kicker">Cara kerja</p><h2>Empat langkah, tanpa bolak-balik.</h2></div><p class="muted">Tidak ada produksi sebelum mockup Anda setujui, dan tidak ada mockup sebelum kami paham penerimanya siapa.</p></div><div class="steps"><article class="step"><span class="step-number">01</span><h3>Brief</h3><p>Anda kirim momen, jumlah penerima, dan budget lewat WhatsApp, email, atau kalkulator di atas.</p><time>Hari ke-0</time></article><article class="step"><span class="step-number">02</span><h3>Rekomendasi</h3><p>Kami kirim 3-5 opsi paket lengkap dengan rincian harga, MOQ, dan estimasi kirim.</p><time>1 hari kerja</time></article><article class="step"><span class="step-number">03</span><h3>Mockup</h3><p>Desain penempatan logo dan kemasan, gratis. Revisi sampai Anda dan atasan Anda setuju.</p><time>1-3 hari kerja</time></article><article class="step"><span class="step-number">04</span><h3>Produksi & kirim</h3><p>Produksi berjalan dengan update foto QC, lalu dikirim ke satu atau banyak alamat cabang.</p><time>7-21 hari kerja</time></article></div></div></section>
        <section id="faq" class="section"><div class="container faq-grid"><div><p class="kicker">FAQ</p><h2>Pertanyaan yang biasanya muncul sebelum mulai.</h2></div><div><details open><summary>Berapa minimum order Hervent?</summary><p>Minimum order mulai dari 50 pcs, namun beberapa produk premium tersedia mulai 25 pcs. Tim kami akan memberi opsi terbaik untuk kebutuhan Anda.</p></details><details><summary>Apakah bisa kirim ke banyak alamat?</summary><p>Bisa. Kami mendukung pengiriman ke kantor pusat, cabang, maupun alamat penerima individual di seluruh Indonesia.</p></details><details><summary>Berapa lama proses produksinya?</summary><p>Estimasi produksi 7-21 hari kerja setelah mockup disetujui, tergantung produk dan jumlah pesanan.</p></details><details><summary>Apakah desain dan mockup dikenakan biaya?</summary><p>Tidak. Desain penempatan logo dan mockup kemasan kami berikan gratis sebelum Anda memutuskan produksi.</p></details></div></div></section>
        <section class="contact-cta"><div class="container contact-cta-panel"><div class="contact-cta-main"><p class="kicker">Jadi partner kami</p><h2>Reputasi brand Anda adalah prioritas kami.</h2><p>Kirim tanggal acara dan jumlah penerima. Kami balas dengan opsi yang masih realistis dikerjakan sampai tanggal itu.</p><div class="contact-actions"><a class="button button-light consultation-button" href="https://wa.me/62811912502" target="_blank"><span class="button-icon">&#9993;</span>WhatsApp 0811-912-502</a><a class="contact-email" href="mailto:cs@hervent.co.id">cs@hervent.co.id &#8594;</a></div></div><div class="contact-address"><span class="address-pin">&#9678;</span><p class="kicker">Kantor pusat — Bandung</p><h3>Komplek Istana Kawaluyaan</h3><p>RW04, Jl. Kawaluyaan Indah XVII No.11, Jatisari, Buahbatu, Kota Bandung 40286</p></div></div></section>
    </main>
    <footer id="kontak"><div class="container"><div class="footer-grid"><div><a class="brand" href="#beranda"><span class="brand-mark">H</span><span>HERVENT<small>REPRESENT YOUR VALUE</small></span></a><p>PT Aventama Hervent Solusindo. Corporate gift, promotional merchandise, dan souvenir kantor custom sejak 2009.</p><p><a href="https://wa.me/62811912502">WhatsApp</a> &nbsp; <a href="https://www.instagram.com/hervent.co.id/">Instagram</a> &nbsp; <a href="https://www.tiktok.com/@hervent.co.id">TikTok</a></p></div><div><h3>Tautan cepat</h3><ul><li><a href="#beranda">Beranda</a></li><li><a href="#produk">Kategori produk</a></li><li><a href="#keunggulan">Koleksi unggulan</a></li><li><a href="#kalkulator">Hitung estimasi budget</a></li><li><a href="#proses">Cara kerja</a></li></ul></div><div><h3>Hubungi kami</h3><ul><li><a href="tel:02287324188">(022) 87324188</a></li><li><a href="https://wa.me/62811912502">0811-912-502</a></li><li><a href="mailto:cs@hervent.co.id">cs@hervent.co.id</a></li><li>Bandung
        </li></ul></div><div><h3>Jam operasional</h3><p>Sen-Jum 09.00-17.00<br>Sab 09.00-12.00</p><p>WhatsApp aktif 24/7</p></div></div><div class="footer-bottom"><span>&copy; {{ date('Y') }} HERVENT - PT Aventama Hervent Solusindo</span><span>Represent your value.</span></div></div></footer>
    <a class="floating-wa" href="https://wa.me/62811912502" target="_blank" aria-label="Chat WhatsApp">&#9742;</a>
+</body>
+</html>
